[package]
name = "sepehr-scanner"
version = "1.0.0"
description = "Sepehr Scanner - Lightweight CF Scanner"
authors = ["Plugtech"]
edition = "2021"

[lib]
name = "sepehr_scanner_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
path = "src/main.rs"

[build-dependencies]
tauri-build = "2.0.0"

[dependencies]
tauri = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"